# Generated by Django 2.1.7 on 2019-03-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the chart', max_length=64),
        ),
    ]
