# Generated by Django 3.0.4 on 2020-03-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_guide_writer',
            field=models.BooleanField(default=False, help_text='Is a recognized guide writer'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_simulationcraft_developer',
            field=models.BooleanField(default=False, help_text='Is a SimulationCraft developer'),
        ),
        migrations.AddField(
            model_name='user',
            name='patron_level',
            field=models.CharField(blank=True, help_text='Patron Tier', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='patron_name',
            field=models.CharField(blank=True, help_text='Patron Name', max_length=100),
        ),
    ]
