# Generated by Django 3.0.4 on 2020-03-21 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_website', '0002_auto_20200321_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='patron_level',
            new_name='patron_tier',
        ),
    ]
