# Generated by Django 2.1.7 on 2019-03-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_website', '0002_simulation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='tokenized_name',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faction',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
