# Generated by Django 2.1.7 on 2019-03-31 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_website', '0003_auto_20190331_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fightstyle',
            name='pretty_name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='fightstyle',
            name='tokenized_name',
            field=models.CharField(max_length=32),
        ),
    ]
