# Generated by Django 3.0.4 on 2020-03-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_website', '0003_auto_20200321_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='patron_uuid',
            field=models.CharField(blank=True, help_text='Patron UUID', max_length=36),
        ),
    ]
