# Generated by Django 2.1.8 on 2019-04-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_website', '0004_auto_20190331_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='progress',
            field=models.PositiveSmallIntegerField(help_text="0-100, but 100 doesn't mean, that the data is available. Simulation reached 100%, though."),
        ),
        migrations.AlterField(
            model_name='queue',
            name='state',
            field=models.CharField(choices=[('PENDING', 'pending'), ('INPROGRESS', 'in progress'), ('DONE', 'done'), ('ERROR', 'error')], max_length=20),
        ),
    ]
