# Generated by Django 3.0.4 on 2020-03-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_website', '0004_user_patron_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='custom_profile',
            field=models.TextField(blank=True, help_text='Define your own character here, instead of using the standard profile (your input will overwrite the standard profile). Paste your <a href="https://mods.curse.com/addons/wow/simulationcraft" target="_blank">SimulationCraft</a> /simc output into this element.', max_length=10000),
        ),
    ]
