# Generated by Django 3.1.1 on 2020-09-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_website', '0005_auto_20200322_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationtype',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Removes SimulationType from being generated.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
