# Generated by Django 3.1.3 on 2020-11-26 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_website', '0006_auto_20200926_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to=settings.AUTH_USER_MODEL),
        ),
    ]
