# Generated by Django 5.1.6 on 2025-03-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general_website", "0007_auto_20201126_0943"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulation",
            name="custom_apl",
            field=models.TextField(
                blank=True, help_text="Define your characters APL.", max_length=65536
            ),
        ),
        migrations.AlterField(
            model_name="simulation",
            name="custom_fight_style",
            field=models.TextField(
                blank=True, help_text="Define your own fight_style.", max_length=65536
            ),
        ),
        migrations.AlterField(
            model_name="simulation",
            name="custom_profile",
            field=models.TextField(
                blank=True,
                help_text='Define your own character here, instead of using the standard profile (your input will overwrite the standard profile). Paste your <a href="https://www.curseforge.com/wow/addons/simulationcraft" target="_blank">SimulationCraft</a> /simc output into this element.',
                max_length=10000,
            ),
        ),
    ]
