# Generated by Django 2.1.8 on 2019-04-24 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_website', '0010_auto_20190421_0205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simulation',
            old_name='character_input',
            new_name='custom_profile',
        ),
    ]
