# Generated by Django 3.0.3 on 2020-03-07 09:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('general_website', '0011_auto_20190424_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fightstyle',
            old_name='pretty_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='race',
            old_name='pretty_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='simulation',
            old_name='fight_style_input',
            new_name='custom_fight_style',
        ),
        migrations.RenameField(
            model_name='wowclass',
            old_name='pretty_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='wowspec',
            old_name='pretty_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='race',
            name='faction',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='uuid',
        ),
        migrations.AddField(
            model_name='race',
            name='factions',
            field=models.ManyToManyField(related_name='races', to='general_website.Faction'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='custom_apl',
            field=models.TextField(blank=True, help_text='Define your characters APL.', max_length=2048),
        ),
        migrations.AlterField(
            model_name='result',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Uuid used to identify a specific simulation Result.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Uuid used to identify a specific Simulation.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Uuid used to identify a User.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wowclass',
            name='races',
            field=models.ManyToManyField(related_name='wow_classes', to='general_website.Race'),
        ),
    ]
