# Generated by Django 2.1.2 on 2018-11-16 08:55

from django.db import migrations


# def rename_example_to_bloodmallet(apps, schema_editor):
#     Pages = apps.get_model('')

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        #migrations.RunPython(rename_example_to_bloodmallet),
    ]
