# Generated by Django 2.1.8 on 2019-04-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_website', '0006_auto_20190410_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bloodytext',
            field=models.CharField(blank=True, default='', max_length=10),
            preserve_default=False,
        ),
    ]
