# Generated by Django 2.1.8 on 2019-04-20 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_website', '0007_auto_20190420_0925'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='generalresult',
            unique_together={('wow_class', 'wow_spec', 'simulation_type', 'fight_style')},
        ),
    ]
