# Generated by Django 2.1.8 on 2019-04-21 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_website', '0009_auto_20190420_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalresult',
            name='wow_spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_result', to='general_website.WowSpec'),
        ),
    ]
